In [39]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('places.csv',encoding='latin1')
data.head()

,state,city,popular_destination,latitude,longitude,interest,google_rating,price_fare
0,Delhi,Delhi,India Gate,28.612912,77.229510,Cultural & Heritage Sites,4.6,0
1,Delhi,Delhi,Humayun's Tomb,28.593285,77.250749,Cultural & Heritage Sites,4.5,30
2,Delhi,Delhi,Akshardham Temple,28.612673,77.277262,Religious & Spiritual Pilgrimages,4.6,60
3,Delhi,Delhi,Waste to Wonder Park,28.592694,77.256972,Adventure & Outdoor Activities,4.1,50
4,Delhi,Delhi,Jantar Mantar,28.627055,77.216627,"Arts, Science & Literature Attractions",4.2,15

In [3]:
data['state'].unique()

array(['Delhi', 'Maharastra', 'Karnataka', 'Telangana', 'West Bengal',
       'Goa', 'Gujrat', 'Gujarat', 'Rajasthan', 'Punjab', 'Kerala',
       'Kerala ', 'Karanataka', 'Maharashtra', 'Maharahtra',
       'Madhya Pradesh', 'Himachal Pradesh', 'Uttarakhand',
       'Uttar Pradesh', 'Jammu and Kashmir', 'Ladakh', 'Odisha',
       'Tamil Nadu', 'Andhra Pradesh', 'Sikkim', 'Assam',
       'Arunachal Pradesh', 'Tripura', 'Nagaland', 'Meghalaya',
       'Chhattisgarh', 'Jharkhand', 'Bihar', 'Haryana', 'Puducherry',
       'Andaman and Nicobar Islands', 'Daman and Diu'], dtype=object)

In [4]:
data['state'].unique()

array(['Delhi', 'Maharastra', 'Karnataka', 'Telangana', 'West Bengal',
       'Goa', 'Gujrat', 'Gujarat', 'Rajasthan', 'Punjab', 'Kerala',
       'Kerala ', 'Karanataka', 'Maharashtra', 'Maharahtra',
       'Madhya Pradesh', 'Himachal Pradesh', 'Uttarakhand',
       'Uttar Pradesh', 'Jammu and Kashmir', 'Ladakh', 'Odisha',
       'Tamil Nadu', 'Andhra Pradesh', 'Sikkim', 'Assam',
       'Arunachal Pradesh', 'Tripura', 'Nagaland', 'Meghalaya',
       'Chhattisgarh', 'Jharkhand', 'Bihar', 'Haryana', 'Puducherry',
       'Andaman and Nicobar Islands', 'Daman and Diu'], dtype=object)

In [5]:

data['state'] = data['state'].str.lower().str.strip()
data['state'].unique().shape

(36,)

In [6]:
data['state'].duplicated().sum()

np.int64(983)

In [7]:
state_mapping = {
    "maharastra": "maharashtra",
    "maharahtra": "maharashtra",
    "gujrat": "gujarat",
    "karanataka": "karnataka",
    "kerala ": "kerala"
}

data['state'] = data['state'].replace(state_mapping)
data['state'].unique()

array(['delhi', 'maharashtra', 'karnataka', 'telangana', 'west bengal',
       'goa', 'gujarat', 'rajasthan', 'punjab', 'kerala',
       'madhya pradesh', 'himachal pradesh', 'uttarakhand',
       'uttar pradesh', 'jammu and kashmir', 'ladakh', 'odisha',
       'tamil nadu', 'andhra pradesh', 'sikkim', 'assam',
       'arunachal pradesh', 'tripura', 'nagaland', 'meghalaya',
       'chhattisgarh', 'jharkhand', 'bihar', 'haryana', 'puducherry',
       'andaman and nicobar islands', 'daman and diu'], dtype=object)

In [8]:
data.rename(columns={'popular_destination' : 'destination'},inplace=True)

In [9]:
def get_regions(state):
    state = str(state).lower().strip()
    north = ["himachal pradesh", "uttarakhand", "punjab", "jammu and kashmir", "ladakh", "haryana", "delhi"]
    south = ["kerala", "tamil nadu", "karnataka", "andhra pradesh", "telangana"]
    east = ["west bengal", "odisha", "bihar", "jharkhand"]
    west = ["rajasthan", "gujarat", "goa", "maharashtra"]
    northeast = ["assam", "meghalaya", "sikkim", "nagaland", "tripura", "arunachal pradesh"]

    if state in north: 
        return "North"
    elif state in south:
        return "South"
    elif state in east:
        return "East"
    elif state in west:
        return "West"
    elif state in northeast:
        return "North-East"
    else:
        return "Unknown"


data['region'] = data['state'].apply(get_regions)

In [10]:
data['region'].unique()

array(['North', 'West', 'South', 'East', 'Unknown', 'North-East'],
      dtype=object)

In [11]:
data['interest'] = data['interest'].str.replace("\t","")
data['interest'] = data['interest'].str.strip().str.lower()

In [12]:
data['interest_list'] = data['interest'].str.split(',')

In [13]:
data.head()

,state,city,destination,latitude,longitude,interest,google_rating,price_fare,region,interest_list
0,delhi,Delhi,India Gate,28.612912,77.229510,cultural & heritage sites,4.6,0,North,[cultural & heritage sites]
1,delhi,Delhi,Humayun's Tomb,28.593285,77.250749,cultural & heritage sites,4.5,30,North,[cultural & heritage sites]
2,delhi,Delhi,Akshardham Temple,28.612673,77.277262,religious & spiritual pilgrimages,4.6,60,North,[religious & spiritual pilgrimages]
3,delhi,Delhi,Waste to Wonder Park,28.592694,77.256972,adventure & outdoor activities,4.1,50,North,[adventure & outdoor activities]
4,delhi,Delhi,Jantar Mantar,28.627055,77.216627,"arts, science & literature attractions",4.2,15,North,"[arts, science & literature attractions]"

In [14]:
def assign_type(interest_list):
    for interest in interest_list:
        interest = interest.strip()

        if "beach" in interest:
            return "beach"
        elif "adventure" in interest:
            return "adventure"
        elif "wildlife" in interest or "natural" in interest:
            return "wildlife"
        elif "heritage" in interest or "cultural" in interest:
            return "heritage"
        elif "religious" in interest or "spirtual" in interest:
            return "religious"
        
    return "city"

In [15]:
data['type'] = data['interest_list'].apply(assign_type)

In [16]:
data[['interest','interest_list','type','destination']].head(10)

,interest,interest_list,type,destination
0,cultural & heritage sites,[cultural & heritage sites],heritage,India Gate
1,cultural & heritage sites,[cultural & heritage sites],heritage,Humayun's Tomb
2,religious & spiritual pilgrimages,[religious & spiritual pilgrimages],religious,Akshardham Temple
3,adventure & outdoor activities,[adventure & outdoor activities],adventure,Waste to Wonder Park
4,"arts, science & literature attractions","[arts, science & literature attractions]",city,Jantar Mantar
5,shopping & markets,[shopping & markets],city,Chandni Chowk
6,religious & spiritual pilgrimages,[religious & spiritual pilgrimages],religious,Lotus Temple
7,cultural & heritage sites,[cultural & heritage sites],heritage,Red Fort
8,cultural & heritage sites,[cultural & heritage sites],heritage,Agrasen ki Baoli
9,natural landscapes & wildlife,[natural landscapes & wildlife],wildlife,Sunder Nursery

In [17]:
def assign_activities(type):

    if type == "mountain":
        return "trekking,snow,adventure,viewpoints"

    elif type == "beach":
        return "beach,water sports,nightlife,relaxation"

    elif type == "heritage":
        return "culture,forts,shopping,history"

    elif type == "religious":
        return "temple,spiritual,peace"

    elif type == "wildlife":
        return "safari,photography,nature"

    elif type == "adventure":
        return "trekking,rafting,paragliding"

    else:
        return "exploration,local experience"

In [18]:
data["activities"] = data["type"].apply(assign_activities)

In [19]:
data.head()

,state,city,destination,latitude,longitude,interest,google_rating,price_fare,region,interest_list,type,activities
0,delhi,Delhi,India Gate,28.612912,77.229510,cultural & heritage sites,4.6,0,North,[cultural & heritage sites],heritage,"culture,forts,shopping,history"
1,delhi,Delhi,Humayun's Tomb,28.593285,77.250749,cultural & heritage sites,4.5,30,North,[cultural & heritage sites],heritage,"culture,forts,shopping,history"
2,delhi,Delhi,Akshardham Temple,28.612673,77.277262,religious & spiritual pilgrimages,4.6,60,North,[religious & spiritual pilgrimages],religious,"temple,spiritual,peace"
3,delhi,Delhi,Waste to Wonder Park,28.592694,77.256972,adventure & outdoor activities,4.1,50,North,[adventure & outdoor activities],adventure,"trekking,rafting,paragliding"
4,delhi,Delhi,Jantar Mantar,28.627055,77.216627,"arts, science & literature attractions",4.2,15,North,"[arts, science & literature attractions]",city,"exploration,local experience"

In [20]:
def assign_budget(price):

    if price == 0:
        return "low"

    elif price < 50:
        return "low"

    elif price < 200:
        return "medium"

    elif price < 500:
        return "high"

    else:
        return "luxury"

In [21]:
data["budget_category"] = data["price_fare"].apply(assign_budget)

In [22]:
data['budget_category'].unique()

array(['low', 'medium', 'luxury', 'high'], dtype=object)

In [27]:
data['type'].unique()

array(['heritage', 'religious', 'adventure', 'city', 'wildlife'],
      dtype=object)

In [33]:
def assign_season(type):

    if type == "mountain" or type == "adventure":
        return "summer"
    
    elif type == "beach" or type == "desert" or type == "wildlife":
        return "winter"
    
    elif type == "heritage":
        return "winter"   # sightseeing comfortable

    elif type == "religious":
        return "all" 
    
    else:
        return "All"

In [34]:
data['best_season'] = data['type'].apply(assign_season)

In [37]:
data['rating'] = data['google_rating']

In [40]:
data['popularity_score'] = np.random.randint(50,100, size = len(data))

In [55]:
def generate_description(row):
    return f"{row['destination']} is a {row['type']} destination in {row['state']} known for {row['activities']}."

In [63]:
def get_user_type(type):

    if type == "adventure":
        return "adventure lover"
    
    elif type == "wildlife":
        return "history and cultural lover"
    
    elif type == "heritage":
        return "history and culture lovers"

    elif type == "religious":
        return "spiritual seekers"

    elif type == "city":
        return "explorers and tourists"

    else:
        return "travelers"

In [62]:
def generate_desc(row):

    user_type = get_user_type(row['type'])

    return f"{row['destination']} is a {row['type']} destination in {row['state']} known for {row['activities']}. It is ideal for {user_type}"

In [64]:
data['description'] = data.apply(generate_desc,axis=1)

In [50]:
data = data.drop(columns=["interest_list","google_rating","price_fare","city"])

In [51]:
data.columns

Index(['state', 'destination', 'latitude', 'longitude', 'interest', 'region',
       'type', 'activities', 'budget_category', 'best_season', 'rating',
       'popularity_score', 'description'],
      dtype='object')

In [68]:
data.to_csv("final_destinations.csv", index=False)

In [74]:
data.head()

,state,destination,latitude,longitude,interest,region,type,activities,budget_category,best_season,rating,popularity_score,description
0,delhi,India Gate,28.612912,77.229510,cultural & heritage sites,North,heritage,"culture,forts,shopping,history",low,winter,4.6,53,India Gate is a heritage destination in delhi ...
1,delhi,Humayun's Tomb,28.593285,77.250749,cultural & heritage sites,North,heritage,"culture,forts,shopping,history",low,winter,4.5,80,Humayun's Tomb is a heritage destination in de...
2,delhi,Akshardham Temple,28.612673,77.277262,religious & spiritual pilgrimages,North,religious,"temple,spiritual,peace",medium,all,4.6,84,Akshardham Temple is a religious destination i...
3,delhi,Waste to Wonder Park,28.592694,77.256972,adventure & outdoor activities,North,adventure,"trekking,rafting,paragliding",medium,summer,4.1,71,Waste to Wonder Park is a adventure destinatio...
4,delhi,Jantar Mantar,28.627055,77.216627,"arts, science & literature attractions",North,city,"exploration,local experience",low,All,4.2,83,Jantar Mantar is a city destination in delhi k...

In [73]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1019 entries, 0 to 1018
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   state             1019 non-null   object
 1   destination       1019 non-null   object
 2   latitude          1019 non-null   float64
 3   longitude         1019 non-null   float64
 4   interest          1019 non-null   object
 5   region            1019 non-null   object
 6   type              1019 non-null   object
 7   activities        1019 non-null   object
 8   budget_category   1019 non-null   object
 9   best_season       1019 non-null   object
 10  rating            1019 non-null   float64
 11  popularity_score  1019 non-null   int32
 12  description       1019 non-null   object
dtypes: float64(3), int32(1), object(9)
memory usage: 99.6+ KB

In [23]:
data['interest'].unique()

array(['cultural & heritage sites', 'religious & spiritual pilgrimages',
       'adventure & outdoor activities',
       'arts, science & literature attractions', 'shopping & markets',
       'natural landscapes & wildlife', 'sightseeing & exploration',
       'sports & recreation',
       'natural landscapes & wildlife, sightseeing & exploration',
       'religious & spiritual pilgrimages, cultural & heritage sites',
       'adventure & outdoor activities, sightseeing & exploration',
       'cultural & heritage sites, natural landscapes & wildlife',
       'natural landscapes & wildlife, adventure & outdoor activities',
       'cultural & heritage sites, religious & spiritual pilgrimages',
       'cultural & heritage sites, arts, science & literature attractions',
       'religious & spiritual pilgrimages, sightseeing & exploration',
       'cultural & heritage', 'adventure & outdoor',
       'shopping & markets, arts, science & literature attractions',
       'religious & spiritual pilgrimages, natural landscapes & wildlife',
       'natural landscapes & wildlife, religious & spiritual pilgrimages',
       'sightseeing & exploration, cultural & heritage sites',
       'adventure & outdoor activities,sightseeing & exploration',
       'adventure & outdoor activities, natural landscapes & wildlife',
       'natural landscapes & wildlife,adventure & outdoor activities,  sightseeing & exploration',
       'culinary & food experiences, shopping & markets',
       'cultural & heritage sites, sightseeing & exploration',
       'sightseeing & exploration, natural landscapes & wildlife',
       'arts, science & literature attractions, cultural & heritage sites',
       'arts, science & literature attractions, sightseeing & exploration',
       'natural landscapes & wildlife, adventure & outdoor activities, sightseeing & exploration',
       'cultural & heritage sites, shopping & markets',
       'natural landscapes & wildlife, beach'], dtype=object)

In [24]:
df = pd.read_csv('Expanded_Destinations.csv')
df.head()

,DestinationID,Name,State,Type,Popularity,BestTimeToVisit
0,1,Taj Mahal,Uttar Pradesh,Historical,8.691906,Nov-Feb
1,2,Goa Beaches,Goa,Beach,8.605032,Nov-Mar
2,3,Jaipur City,Rajasthan,City,9.225372,Oct-Mar
3,4,Kerala Backwaters,Kerala,Nature,7.977386,Sep-Mar
4,5,Leh Ladakh,Jammu and Kashmir,Adventure,8.399822,Apr-Jun

In [25]:
columns = [
    "destination",
    "state",
    "region",
    "type",
    "budget_category",
    "best_season",
    "activities",
    "rating",
    "popularity_score",
    "latitude",
    "longitude",
    "description"
]